name: CI

on:
  push:
    branches: [ multicontainers ]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx playwright
        
    - name: Install Playwright browsers
      run: |
        python -m playwright install
        
    - name: Verify imports
      run: |
        python -c "from app.routers import reminders, login, api, root; print('All routers imported successfully')"
        python -c "from app.utils import auth, mysql_storage, exceptions; print('All utils imported successfully')"
        
    - name: Run unit tests
      run: |
        python -m pytest tests/test_unit.py -v
        
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' &&  github.ref == 'refs/heads/multicontainers'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
      continue-on-error: true
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/catty-reminders:latest
          ghcr.io/${{ github.repository_owner }}/catty-reminders:${{ github.sha }}
